url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/tomas-jekyll" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.
# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.text
  - README.md
  - SECURITY.md

theme: jekyll-theme-cayman