---
#-------------------------------
# General Site Settings

title: Tomás Santos
logo: "../assets/images/logo.svg"
description: this is meta description
email: tomaacs2000@gmail.com
phone: +351 961 013 815
copyright: Copyright &copy; 2022 Designed and Developed by Tomás Santos™.

menu:
  - { name: About, link: "/about" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Contact, link: "/contact" }

social:
  - {
      name: instagram,
      username: "@santsan00",
      link: "https://www.instagram.com/santsan00/",
      svg: "",
    }
  - {
      name: linkedin,
      username: "@omassantos7",
      link: "https://www.linkedin.com/in/tom%C3%A1s-santos-7b438322b/",
      svg: "",
    }
  - { name: email, username: "tomaacs2000@gmail.com", svg: "" }

---

