---
title: Tomás Santos
logo: "logo.svg"

menu:
  - { name: About, link: "/about" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Contact, link: "/contact" }

social:
  - {
      name: instagram,
      username: "@santsan00",
      link: "https://www.instagram.com/santsan00/",
      svg: "instagram.svg",
    }
  - {
      name: linkedin,
      username: "@tomassantos7",
      link: "https://www.linkedin.com/in/tom%C3%A1s-santos-7b438322b/",
      svg: "linkedin.svg",
    }
  - { name: email, username: "tomaacs2000@gmail.com", svg: "email.svg" }

---

